/*
 * Copyright 2022 wil.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gt.edu.meso.jui;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 * @author wil
 */
public class Cargador extends Window {
    
    /**
     * Creates new form Cargador
     */
    public Cargador() {
        initComponents();
        componentesAdd();
    }

    @Override
    protected final void componentesAdd() {
        int w = bg.getWidth(),
            h = bg.getHeight();
               
        final ImageIcon icon = new ImageIcon(new ImageIcon(getClass()
                                                            .getResource("/BG/bg01.jpeg"))
                                                            .getImage()
                                                            .getScaledInstance(w, h, Image.SCALE_SMOOTH));
       
        this.bg.setIcon(icon);       
        this.setTitle("Cargador");
        this.setSize(w, h);
        this.center();
    }

    private void start() {
        final Thread thread = new Thread(() -> {
            try {
                Thread.sleep(1500);
            } catch (InterruptedException e) { }
            
            Cargador.this.setVisible(false);
            Cargador.this.dispose();
            
            final Entrada entrada = new Entrada();
            entrada.setVisible(true);
        });
        thread.setDaemon(true);
        thread.start();
    }
    
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        root.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Santos Misahel Yaxón Tuy");
        root.add(jLabel5);
        jLabel5.setBounds(410, 285, 180, 15);

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Javier Alejandro García Aguilón");
        root.add(jLabel3);
        jLabel3.setBounds(410, 300, 180, 19);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Wilson Martín Cabrera Juárez");
        root.add(jLabel1);
        jLabel1.setBounds(410, 270, 190, 15);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("v1.0.0");
        root.add(jLabel4);
        jLabel4.setBounds(20, 70, 170, 19);

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Wizzard");
        root.add(jLabel2);
        jLabel2.setBounds(20, 20, 180, 40);

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        root.add(bg);
        bg.setBounds(0, 0, 590, 330);

        getContentPane().add(root, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
