/*
 * Copyright 2022 wil.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gt.edu.meso.jui.panel;

import gt.edu.meso.Bandas;
import gt.edu.meso.JBanda4;
import gt.edu.meso.JBanda5;
import gt.edu.meso.framework.Resitor2D;
import gt.edu.meso.jui.InfoCalculadoraResistencia;
import gt.edu.meso.jui.JColorListCellRenderer;
import gt.edu.meso.util.JColor;
import gt.edu.meso.util.Notation;
import gt.edu.meso.util.Theme;
import java.awt.Canvas;
import java.awt.Frame;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author wil
 */
public class PanelCalculadora extends javax.swing.JPanel {
    
    private Resitor2D resitor2D;
    private JBanda4 bandas4;
    private JBanda5 bandas5;
    private Frame frame;
        
    /**
     * Creates new form PanelCalculadora
     */
    public PanelCalculadora() {
        initComponents();
        componentesAdd();
    }
    
    /**
     * Se inicializa los componentes adicionales.
     */
    protected final void componentesAdd() {
        jComboBox1.setRenderer(new JColorListCellRenderer(JColorListCellRenderer.TypeComboModel.COLOR_BANDA));
        jComboBox1.setModel(createComboBoxModel(JColorListCellRenderer.TypeComboModel.COLOR_BANDA));

        jComboBox2.setRenderer(new JColorListCellRenderer(JColorListCellRenderer.TypeComboModel.COLOR_BANDA));
        jComboBox2.setModel(createComboBoxModel(JColorListCellRenderer.TypeComboModel.COLOR_BANDA));

        jComboBox3.setRenderer(new JColorListCellRenderer(JColorListCellRenderer.TypeComboModel.COLOR_BANDA));
        jComboBox3.setModel(createComboBoxModel(JColorListCellRenderer.TypeComboModel.COLOR_BANDA));

        jComboBox4.setRenderer(new JColorListCellRenderer(JColorListCellRenderer.TypeComboModel.COLOR_MULTIPLICADOR));
        jComboBox4.setModel(createComboBoxModel(JColorListCellRenderer.TypeComboModel.COLOR_MULTIPLICADOR));

        jComboBox5.setRenderer(new JColorListCellRenderer(JColorListCellRenderer.TypeComboModel.COLOR_TOLERANCIA));
        jComboBox5.setModel(createComboBoxModel(JColorListCellRenderer.TypeComboModel.COLOR_TOLERANCIA));
        
        bandas4 = new JBanda4();
        bandas5 = new JBanda5();
        info.setVisible(false);
        
        setBackground(Theme.getColor("color.dark.panel"));
        set5Bandas(false);
        
        jLabel1.setForeground(Theme.getColor("color.dark.fg"));
        jLabel2.setForeground(Theme.getColor("color.dark.fg"));
        jLabel3.setForeground(Theme.getColor("color.dark.fg"));
        jLabel4.setForeground(Theme.getColor("color.dark.fg"));
        jLabel5.setForeground(Theme.getColor("color.dark.fg"));
        jLabel6.setForeground(Theme.getColor("color.dark.fg"));
        jLabel7.setForeground(Theme.getColor("color.dark.fg"));
        jLabel8.setForeground(Theme.getColor("color.dark.fg"));
        out.setForeground(Theme.getColor("color.dark.fg"));
        
        opcionBanda4.setForeground(Theme.getColor("color.dark.fg"));
        opcionBanda5.setForeground(Theme.getColor("color.dark.fg"));
        jPanel1.setBackground(Theme.getColor("color.dark.panel"));
    }

    public void setView(Canvas canvas, Resitor2D resitor2D) {
        this.resitor2D = resitor2D;
        this.resitor2D.setNoBandas(Resitor2D.ResBanda.CUATRO);
        jScrollPane1.setViewportView(canvas);
    }

    public void setFrame(Frame frame) {
        this.frame = frame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        opcionBanda4 = new javax.swing.JRadioButton();
        opcionBanda5 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        out = new javax.swing.JLabel();
        info = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cantidad de bandas:");

        buttonGroup1.add(opcionBanda4);
        opcionBanda4.setForeground(new java.awt.Color(0, 0, 0));
        opcionBanda4.setSelected(true);
        opcionBanda4.setText("4 bandas");
        opcionBanda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBanda4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opcionBanda5);
        opcionBanda5.setForeground(new java.awt.Color(0, 0, 0));
        opcionBanda5.setText("5 Bandas");
        opcionBanda5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBanda5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Salida");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("1°. Banda de color");

        jComboBox1.setFocusable(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("2°. Banda de color");

        jComboBox2.setFocusable(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("3°. Banda de color");

        jComboBox3.setFocusable(false);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setFocusable(false);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Multiplicador  ");

        jLabel7.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tolerancia");

        jComboBox5.setFocusable(false);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jScrollPane1.setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Valor de la resistencia:");

        out.setFont(new java.awt.Font("Source Sans Pro Black", 0, 28)); // NOI18N
        out.setForeground(new java.awt.Color(0, 0, 0));
        out.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        out.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addComponent(out, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        info.setForeground(new java.awt.Color(0, 102, 204));
        info.setText("Mas Informacion");
        info.setBorder(null);
        info.setBorderPainted(false);
        info.setContentAreaFilled(false);
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info.setOpaque(true);
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        jLabel9.setText(" ");

        jLabel10.setText(" ");
        jLabel10.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opcionBanda4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opcionBanda5))
                            .addComponent(jLabel7)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionBanda4)
                    .addComponent(opcionBanda5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void set5Bandas(boolean visible) {
        jLabel5.setVisible(visible);
        jComboBox3.setVisible(visible);
    }
    
    private void printf() {
        Notation notation = null;        
        if (opcionBanda4.isSelected()) {
            if (bandas4.isPrintf()) {
                double tol = bandas4.getTolerance().getScaleTolerance();
                notation   = Notation.determine(bandas4.getOhms()); 
                
                if (tol >= 1) {
                    out.setText(notation.getUnscaleNumber() + notation.getPrefix().getPrefix() + " Ohms " + ((int )tol) + '%');
                } else {
                    out.setText(notation.getUnscaleNumber() + notation.getPrefix().getPrefix() + " Ohms " + tol + '%');
                }
                info.setVisible(true);
            } else {
                info.setVisible(false);
            }
        } else {
            if (opcionBanda5.isSelected()) {
                if (bandas5.isPrintf()) {
                    double tol = bandas5.getTolerance().getScaleTolerance();
                    notation   = Notation.determine(bandas5.getOhms()); 
                    
                    if (tol >= 1) {
                        out.setText(notation.getUnscaleNumber() + notation.getPrefix().getPrefix() + " Ohms " + ((int )tol) + '%');
                    } else {
                        out.setText(notation.getUnscaleNumber() + notation.getPrefix().getPrefix() + " Ohms " + tol + '%');
                    }
                    info.setVisible(true);
                } else {
                    info.setVisible(false);
                }
            }
        }
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        final Object item = jComboBox1.getSelectedItem();
        if (item != null && (item instanceof JColor)) {       
            jComboBox1.setBackground(((JColor) item).getAWTColor());
            
            bandas4.setBanda1((JColor) item);
            bandas5.setBanda1((JColor) item);
            
            if (opcionBanda4.isSelected()) {                
                resitor2D.setBandas(bandas4);
            } else {                
                resitor2D.setBandas(bandas5);
            }
            printf();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        final Object item = jComboBox2.getSelectedItem();
        if (item != null && (item instanceof JColor)) {
            jComboBox2.setBackground(((JColor) item).getAWTColor());
            
            bandas4.setBanda2((JColor) item);
            bandas5.setBanda2((JColor) item);
            
            if (opcionBanda4.isSelected()) {                
                resitor2D.setBandas(bandas4);
            } else {                
                resitor2D.setBandas(bandas5);
            }
            printf();
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        final Object item = jComboBox3.getSelectedItem();
        if (item != null && (item instanceof JColor)) {
            jComboBox3.setBackground(((JColor) item).getAWTColor());
            
            if (opcionBanda5.isSelected()) {
                bandas5.setBanda3((JColor) item);
                resitor2D.setBandas(bandas5);
            }
            printf();
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        final Object item = jComboBox4.getSelectedItem();
        if (item != null && (item instanceof JColor)) {
            jComboBox4.setBackground(((JColor) item).getAWTColor());
            
            bandas4.setMultiplier((JColor) item);
            bandas5.setMultiplier((JColor) item);
            
            if (opcionBanda4.isSelected()) {                
                resitor2D.setBandas(bandas4);
            } else {                
                resitor2D.setBandas(bandas5);
            }
            printf();
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        final Object item = jComboBox5.getSelectedItem();
        if (item != null && (item instanceof JColor)) {
            jComboBox5.setBackground(((JColor) item).getAWTColor());
            
            bandas4.setTolerance((JColor) item);
            bandas5.setTolerance((JColor) item);
            
            if (opcionBanda4.isSelected()) {                
                resitor2D.setBandas(bandas4);
            } else {                
                resitor2D.setBandas(bandas5);
            }
            printf();
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void opcionBanda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBanda4ActionPerformed
        if (opcionBanda4.isSelected()) {
            set5Bandas(false);
            
            if (resitor2D != null) {
                resitor2D.setBandas(bandas4);
                resitor2D.setNoBandas(Resitor2D.ResBanda.CUATRO);
            }
            printf();
        }
    }//GEN-LAST:event_opcionBanda4ActionPerformed

    private void opcionBanda5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBanda5ActionPerformed
        if (opcionBanda5.isSelected()) {
            set5Bandas(true);
            
            if (resitor2D != null) {
                resitor2D.setBandas(bandas5);
                resitor2D.setNoBandas(Resitor2D.ResBanda.CINCO);
            }
            printf();
        }
    }//GEN-LAST:event_opcionBanda5ActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        final InfoCalculadoraResistencia icr = new InfoCalculadoraResistencia(frame, true);
        icr.setResistencia(resitor2D);
        icr.center(frame);
        icr.setVisible(true);
    }//GEN-LAST:event_infoActionPerformed

    /**
     * Metodo encargado de crera el modelo de colores que contendra cada
     * lista desplegable.
     * @param model Tipo de modelo de color.
     * @return Modelo para el ComboBox.
     */
    private DefaultComboBoxModel<JColor> createComboBoxModel(JColorListCellRenderer.TypeComboModel model) {
        switch (model) {
            case COLOR_BANDA:
                return new DefaultComboBoxModel<>(Bandas.BANDA);
            case COLOR_MULTIPLICADOR:
                return new DefaultComboBoxModel<>(Bandas.MULTIPLICADOR);
            case COLOR_TOLERANCIA:
                return new DefaultComboBoxModel<>(Bandas.TOLERANCIA);
            default:
                throw new AssertionError();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton info;
    private javax.swing.JComboBox<JColor> jComboBox1;
    private javax.swing.JComboBox<JColor> jComboBox2;
    private javax.swing.JComboBox<JColor> jComboBox3;
    private javax.swing.JComboBox<JColor> jComboBox4;
    private javax.swing.JComboBox<JColor> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton opcionBanda4;
    private javax.swing.JRadioButton opcionBanda5;
    private javax.swing.JLabel out;
    // End of variables declaration//GEN-END:variables
}
